### ISSUE TITLE
关于初始化与销毁

### ISSUE THREAD

**Issue by jovichin** [Jedi-Lee/jQuery.pwd#2]
作者不知道现在是否还更新这个插件，作为前端初学者，有几点小小的建议，不知道作者能否完善一下。
目前这个插件是结合lay弹窗在用，那么问题来了。
同一个页面中可能会有多个弹窗中使用这个密码输入插件。点击一个元素，弹窗弹出，其中包含这个密码输入插件，如果输入了一次，但是关闭了弹窗，再点击其他元素，打开弹窗，那么这次弹窗中的密码输入插件，不为空，还是显示的上一次输入过的。所以，不知道作者能否加个初始化以及销毁的方法，这样我就可以在弹窗触发时候去初始化这个密码插件，并在关闭弹窗时候，销毁这个插件，在另一个激活弹窗的地方重新初始化一下。
所以特别期待作者能够继续完善整个弹窗插件，真的很好用，十分感谢。
（不知道我表达清楚没）

**Comment by sansi-lcj** [comment]
没想到这么些年过去了还有人在用这个插件，这个插件也是我刚学前端的时候写的，很粗糙。我找个时间重写一下这个插件。

**Comment by jovichin** [comment]
没想到作者真回复了，这么多年过去，我以为作者不会看到了，确实，因为没有找到更好的仿支付宝密码输入插件。谢谢作者回复，我如何重新设置焦点参数active呢？我想在关闭弹窗的回调中，将active，设为0，这样再次打开弹窗显示输入密码时候，就没问题，现在就是在弹窗关闭回调中清除了输入密码input的值，但是不知道该怎么将焦点参数active重新设置

**Comment by sansi-lcj** [comment]
这么做，这个组件会将input框替换为一个id为pwdcontainer的div，你在关闭弹窗的时候将得到的密码保存下来，然后把这个div整体remove，然后插入一个新的input再调用一次pwd去初始化。
我这周末重写一下这个插件，加入你需要的初始化跟销毁功能。

**Comment by jovichin** [comment]
好的作者，十分感谢你能回复我！十分感谢！

**Comment by sansi-lcj** [comment]
我修改了组件，添加了重置和销毁的方法。

**Comment by jovichin** [comment]
十分感谢作者！！！
